backend:
  host: 127.0.0.1
  port: 8000
  use_ssl: false
  timeout: 30
  reconnect_interval: 5
score_version: v3
gui:
  theme: dark
  acrylic_enabled: true
  font_family: Pretendard
  font_size: 12
  opacity: 0.95
  acrylic_map_alpha: 145
  particle_alpha: 0.5
  tint_color: '#151520'
  background_effect: constellation
chart:
  default_timeframe: 5m
  show_vwap: true
  show_stop_lines: true
  show_trade_markers: true
  theme: dark
window:
  width: 1920
  height: 1080
  remember_position: true
  always_on_top: false
tables:
  tier1_column_widths:
  - 0
  - 73
  - 50
  - 56
  - 55
  tier2_column_widths:
  - 0
  - 50
  - 46
  - 45
  - 45
  - 40
  - 45
